(function(){
'use strict';
const D=window.GAME_DATA,$=id=>document.getElementById(id),{M,START,APPROACHES,GOALS,POLICIES:P,EVENTS,SURPRISE}=D;
const MAX_POLICIES=3;
const PRIMARY={youth:['youth'],child:['child'],senior:['senior'],industry:['industry'],tourism:['tourism'],connected:['connection','equity','acceptance'],learning:['connection','youth']};
M.acceptance={n:'住民の納得感',i:'🗣️'}; START.acceptance=56;
Object.values(GOALS).forEach(g=>{if(g.t.acceptance==null)g.t.acceptance=60});
if(!P.some(p=>p.id==='parkCommons'))P.push({id:'parkCommons',icon:'🌳',name:'公園・公共空間を「居場所」にする',cost:24,upkeep:5,tags:['child','distributed','publicspace'],focus:['child','connection','senior'],e:{child:7,connection:6,senior:2,equity:2,acceptance:3,fatigue:2},desc:'公園や広場に日陰・ベンチ・遊び・交流の仕掛けを入れ、世代を越えて使える場所にする。'});
const CONCERNS=[
{id:'parks',icon:'🌳',name:'公園・遊び場',metric:'child',matchIds:['parkCommons','childPlace','multiGen'],matchTags:['publicspace'],voice:'近くで、子どもも大人も気軽に過ごせる場所がほしい。'},
{id:'childcare',icon:'👶',name:'子育て支援',metric:'child',matchIds:['childPlace','parentNet','parkCommons'],matchTags:['child'],voice:'制度だけでなく、ふだん頼れる場所や人がほしい。'},
{id:'youth',icon:'🧑‍🎓',name:'若者の居場所・参加',metric:'youth',matchIds:['youthDay','youthNight','career'],matchTags:['youth'],voice:'若い人が参加できる時間や役割がもっとあっていい。'},
{id:'senior',icon:'👴',name:'高齢者の交流・移動',metric:'senior',matchIds:['seniorRole','multiGen','microDistrict','parkCommons'],matchTags:['senior'],voice:'近くで出かける理由や、人と話せる機会がほしい。'},
{id:'jobs',icon:'🏭',name:'仕事・地域産業',metric:'industry',matchIds:['career','bizChallenge','bizWelfare','market'],matchTags:['business','jobs'],voice:'町の中の仕事や店が元気になる取り組みがほしい。'},
{id:'tourism',icon:'🏝️',name:'観光・にぎわい',metric:'tourism',matchIds:['cultureTour','market'],matchTags:['tourism'],voice:'南風原らしさを外から来る人にも知ってほしい。'},
{id:'district',icon:'🗺️',name:'地区ごとの公平さ',metric:'equity',matchIds:['multiGen','microDistrict','coordinator','welcome'],matchTags:['distributed'],voice:'中心だけでなく、住んでいる地区でも参加しやすくしてほしい。'},
{id:'belonging',icon:'🤝',name:'孤立しにくいつながり',metric:'connection',matchIds:['welcome','coordinator','multiGen','bizWelfare','parkCommons'],matchTags:['mobility','welfare'],voice:'一人でも入りやすく、知り合いがいなくても参加できる場がほしい。'}
];
const COMBOS=[
{ids:['youthNight','career'],name:'若者の声→仕事へ',e:{youth:3,stay:3,industry:2,acceptance:2},type:'synergy'},
{ids:['childPlace','parentNet'],name:'居場所×専門職連携',e:{child:3,connection:2,acceptance:2},type:'synergy'},
{ids:['parkCommons','multiGen'],name:'公園×多世代交流',e:{connection:3,senior:2,child:2,acceptance:2},type:'synergy'},
{ids:['coordinator','microDistrict'],name:'調整役×出張型',e:{equity:3,connection:2,fatigue:-2},type:'synergy'},
{ids:['market','cultureTour'],name:'マーケット×文化ツアー',e:{tourism:4,industry:3,fatigue:2},type:'synergy'},
{ids:['centralHub','cultureTour'],name:'中心地区への集中',e:{equity:-4,acceptance:-3,fatigue:2},type:'conflict'},
{ids:['centralHub','market'],name:'中心地区への集中',e:{equity:-3,acceptance:-2},type:'conflict'}
];
let S=null;
const clamp=v=>Math.max(0,Math.min(100,Math.round(v))),pick=a=>a[Math.floor(Math.random()*a.length)],policy=id=>P.find(x=>x.id===id);
function currentLimit(){return S&&S.year===1?2:MAX_POLICIES}
function continuedIds(){return S.active.filter(id=>S.keep[id]!==false)}
function upkeep(){return continuedIds().reduce((a,id)=>a+(policy(id).upkeep||0),0)}
function available(){return Math.max(0,72+S.currentBudgetBonus-upkeep())}
function selectedCost(){return S.selected.reduce((a,id)=>a+policy(id).cost,0)}
function totalPlanned(){return continuedIds().length+S.selected.length}
function slotsLeft(){return Math.max(0,currentLimit()-totalPlanned())}
function trimSelections(){while(S.selected.length&&(selectedCost()>available()||totalPlanned()>currentLimit()))S.selected.pop()}
function approachBonus(p){let m=1,w=[];if(S.approach==='repair'&&(p.tags.includes('repair')||p.tags.includes('jobs')||p.tags.includes('distributed')||p.tags.includes('flexible'))){m*=1.12;w.push('課題解決方針 +12%')}if(S.approach==='strength'&&(p.tags.includes('strength')||p.tags.includes('business')||p.tags.includes('welfare')||p.tags.includes('child'))){m*=1.12;w.push('強み活用方針 +12%')}return{m,w}}
function concernMatch(p,c){return c.matchIds.includes(p.id)||c.matchTags.some(t=>p.tags.includes(t))}
function concernBonus(p){if(!S.concerns)return{m:1,w:[]};let m=1,w=[];S.concerns.slice(0,3).forEach((c,i)=>{if(concernMatch(p,c)){const b=[.20,.10,.05][i];m*=1+b;w.push('住民関心「'+c.name+'」 +'+Math.round(b*100)+'%')}});return{m,w}}
function diminishBonus(p){let streak=0;p.focus.forEach(k=>{streak=Math.max(streak,S.focusStreak[k]||0)});const f=streak===0?1:streak===1?.82:streak===2?.65:streak===3?.50:.40;return{m:f,w:streak?['同じ分野への連続投資 '+(streak+1)+'年目 → ×'+f.toFixed(2)]:[]}}
function localFit(p){let m=1,w=[];if(p.tags.includes('child')){m*=1.15;w.push('子ども人口の厚み +15%')}if(p.tags.includes('daytime')){m*=.78;w.push('町外通勤通学の多さ −22%')}if(p.tags.includes('flexible')){m*=1.15;w.push('夜・オンライン型 +15%')}if(p.tags.includes('jobs')){m*=1.15;w.push('町内仕事づくり +15%')}if(p.tags.includes('business')){m*=1.12;w.push('1,441事業所 +12%')}if(p.tags.includes('welfare')){m*=1.10;w.push('医療・福祉基盤 +10%')}if(p.tags.includes('mobility')){m*=1.10;w.push('転入超過 +10%')}if(p.tags.includes('distributed')){m*=1.12;w.push('地区規模差への対応 +12%')}let a=approachBonus(p);m*=a.m;w=w.concat(a.w);let c=concernBonus(p);m*=c.m;w=w.concat(c.w);let d=diminishBonus(p);m*=d.m;w=w.concat(d.w);if(S.v.fatigue>=80){m*=.62;w.push('担い手疲労で効果−38%')}else if(S.v.fatigue>=65){m*=.78;w.push('担い手疲労で効果−22%')}return{m,w}}
function adjustedEffects(p,fit){return Object.entries(p.e).map(([k,v])=>[k,(k==='fatigue'||k==='acceptance')?v:Math.round(v*fit.m)])}
function generateConcerns(){let arr=CONCERNS.map(c=>{let score=25+Math.random()*20;score+=(65-(S.v[c.metric]||50))*.55;score+=(S.neglect[c.metric]||0)*6;const e=(S.event&&S.event.text)||'';if(c.id==='jobs'&&/(人手不足|地域の店)/.test(e))score+=20;if(c.id==='district'&&/(地区|遠い)/.test(e))score+=20;if(c.id==='youth'&&/(通勤|通学|平日日中)/.test(e))score+=15;if(c.id==='childcare'&&/(転入|引っ越)/.test(e))score+=8;if(c.id==='belonging'&&/(転入|地域のことが分からない)/.test(e))score+=15;if(c.id==='tourism'&&/(台風|イベント)/.test(e))score+=10;return{...c,score}});if((S.focusStreak.child||0)>=2)arr.forEach(x=>{if(['senior','belonging','jobs'].includes(x.id))x.score+=12});if((S.focusStreak.senior||0)>=2)arr.forEach(x=>{if(['childcare','youth','jobs'].includes(x.id))x.score+=10});if((S.focusStreak.industry||0)>=2)arr.forEach(x=>{if(['childcare','senior','district'].includes(x.id))x.score+=9});if((S.focusStreak.tourism||0)>=2)arr.forEach(x=>{if(['district','belonging','childcare'].includes(x.id))x.score+=10});arr.sort((a,b)=>b.score-a.score);const top=arr.slice(0,3),sum=top.reduce((a,b)=>a+b.score,0);top.forEach(x=>x.pct=Math.round(x.score/sum*100));let diff=100-top.reduce((a,b)=>a+b.pct,0);top[0].pct+=diff;return top}
function ensureYearContext(){if(!S.event)S.event=pick(EVENTS);if(!S.concerns)S.concerns=generateConcerns()}
function renderApproaches(){let h=$('approachGrid');Object.entries(APPROACHES).forEach(([k,a],i)=>{let d=document.createElement('div');d.className='choice'+(i===2?' active':'');d.dataset.k=k;d.innerHTML='<b>'+a.icon+' '+a.name+'</b><span class="small">'+a.desc+'</span><div class="rule">'+a.bonus+'</div>';d.onclick=()=>{h.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));d.classList.add('active')};h.appendChild(d)})}
function renderGoals(){let h=$('goalGrid');Object.entries(GOALS).forEach(([k,g],i)=>{let d=document.createElement('div');d.className='choice'+(i===0?' active':'');d.dataset.k=k;let main=Object.entries(g.t).filter(([x])=>!['fatigue','acceptance'].includes(x)).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([x,v])=>M[x].n+' '+v).join(' / ');d.innerHTML='<b>'+g.icon+' '+g.name+'</b><span class="small">'+main+'</span>';d.onclick=()=>{h.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));d.classList.add('active')};h.appendChild(d)})}
function milestone(){return S.year===1?'🌱 1年目：最初の年は、新しく始められる施策は2つまで。':S.year===3?'🏁 3年目：折り返し。住民の関心も、これまでの選択で変わる。':S.year===5?'🏆 最終年：目標・世論・持続性をどう両立する？':'あと'+(6-S.year)+'年。今年の「まちの空気」は昨年と同じとは限りません。'}
function allPlannedIds(){return continuedIds().concat(S.selected)}
function comboAdjust(delta,reasons,ids){COMBOS.forEach(c=>{if(c.ids.every(id=>ids.includes(id))){Object.entries(c.e).forEach(([k,v])=>delta[k]=(delta[k]||0)+v);if(reasons)reasons.push((c.type==='synergy'?'✨ 相乗効果：':'⚠️ 葛藤：')+c.name+' → '+Object.entries(c.e).map(([k,v])=>M[k].n+(v>0?'+':'')+v).join('、'))}})}
function opinionAdjust(delta,reasons,ids){if(!S.concerns)return;S.concerns.forEach((c,i)=>{const met=ids.some(id=>concernMatch(policy(id),c));if(i===0){if(met){delta.acceptance=(delta.acceptance||0)+4;if(c.metric)delta[c.metric]=(delta[c.metric]||0)+1;if(reasons)reasons.push('🗣️ 最重要の住民関心「'+c.name+'」に応えた → 納得感+4')}else{delta.acceptance=(delta.acceptance||0)-5;if(c.metric)delta[c.metric]=(delta[c.metric]||0)-2;if(reasons)reasons.push('🗣️ 最重要の住民関心「'+c.name+'」を後回し → 納得感-5、'+M[c.metric].n+'-2')}}else if(i===1){delta.acceptance=(delta.acceptance||0)+(met?2:-2);if(reasons&&met)reasons.push('住民関心「'+c.name+'」にも対応 → 納得感+2')}})}
function biasAdjust(delta,reasons,ids){const counts={child:0,youth:0,senior:0,industry:0,tourism:0};ids.forEach(id=>policy(id).focus.forEach(k=>{if(counts[k]!=null)counts[k]++}));if(counts.child>=2&&(S.focusStreak.child||0)>=1){delta.acceptance=(delta.acceptance||0)-4;delta.senior=(delta.senior||0)-1;if(reasons)reasons.push('⚖️ 子ども分野への集中が続き、他層から「自分たちへの関心は？」という声 → 納得感-4、高齢者-1')}if(counts.senior>=2&&(S.focusStreak.senior||0)>=1){delta.acceptance=(delta.acceptance||0)-4;delta.youth=(delta.youth||0)-1;if(reasons)reasons.push('⚖️ 高齢者分野への集中が続き、若い世代の納得感が低下 → 納得感-4、若者-1')}if(counts.tourism>=2){delta.acceptance=(delta.acceptance||0)-2;delta.fatigue=(delta.fatigue||0)+2;if(reasons)reasons.push('⚖️ にぎわい施策の集中で、暮らしとの摩擦が発生 → 納得感-2、疲れ+2')}}
function plan(){let delta={},focus=new Set(),nextNeglect={...S.neglect};Object.entries((S.event&&S.event.e)||{}).forEach(([k,v])=>delta[k]=(delta[k]||0)+v);continuedIds().forEach(id=>{let p=policy(id);p.focus.forEach(x=>focus.add(x));Object.entries(p.e).forEach(([k,v])=>{if(!v)return;let q=Math.round(v*.25);if(q===0)q=v>0?1:-1;delta[k]=(delta[k]||0)+q})});S.selected.forEach(id=>{let p=policy(id),fit=localFit(p);p.focus.forEach(x=>focus.add(x));adjustedEffects(p,fit).forEach(([k,v])=>delta[k]=(delta[k]||0)+v)});const ids=allPlannedIds();comboAdjust(delta,null,ids);opinionAdjust(delta,null,ids);biasAdjust(delta,null,ids);const base={youth:1,child:2,senior:1,stay:2,industry:1,tourism:1,equity:2};Object.entries(base).forEach(([k,b])=>{if(focus.has(k)){nextNeglect[k]=0;return}nextNeglect[k]=(nextNeglect[k]||0)+1;let loss=b+Math.max(0,nextNeglect[k]-1);delta[k]=(delta[k]||0)-loss});let projected={...S.v};Object.entries(delta).forEach(([k,v])=>projected[k]=clamp(projected[k]+v));return{delta,projected,nextNeglect}}
function renderMetrics(){let h=$('metricGrid'),g=GOALS[S.goal],pl=plan();h.innerHTML='';Object.entries(M).forEach(([k,m])=>{let now=S.v[k],pred=pl.projected[k],d=pred-now,t=g.t[k],good=k==='fatigue'?d<=0:d>=0,ok=k==='fatigue'?now<=t:now>=t,card=document.createElement('div');card.className='metric'+(k==='fatigue'?' fatigue':'');card.innerHTML='<div class="metricTop"><span class="name">'+m.i+' '+m.n+'</span><b>'+now+' <small>→ '+pred+'</small></b></div><div class="forecastBar '+(good?'good':'bad')+'"><span class="forecast" style="width:'+pred+'%"></span><i style="left:'+now+'%"></i></div><div class="metricFoot"><span class="delta '+(d===0?'flat':good?'goodText':'badText')+'">'+(d>0?'+':'')+d+'</span><span>目標 '+(k==='fatigue'?'≤':'≥')+t+(ok?' ✓':'')+'</span></div>';h.appendChild(card)})}
function renderPulse(){const h=$('residentPulse');h.innerHTML='<div class="pulseTop"><div><h2>🗣️ 今年の住民関心</h2><p class="small">ゲーム内の仮想世論です。町の状態・これまでの施策・今年の出来事から毎年変わります。</p></div><span class="pulseYear">'+S.year+'年目</span></div><div class="pulseGrid">'+S.concerns.map((c,i)=>'<div class="pulseItem rank'+(i+1)+'"><div class="pulseLabel"><b>'+(i+1)+'位 '+c.icon+' '+c.name+'</b><strong>'+c.pct+'%</strong></div><div class="pulseBar"><span style="width:'+c.pct+'%"></span></div><div class="small">'+c.voice+'</div></div>').join('')+'</div><div class="pulseNote">1位の関心に応えると施策効果と「住民の納得感」が上がりやすく、無視すると下がります。ただし、人気のある施策だけを続けると別の層の不満が強まることがあります。</div>'}
function renderContinuations(){let box=$('continuationList');if(!S.active.length){$('continuationCard').classList.add('hidden');box.innerHTML='';return}$('continuationCard').classList.remove('hidden');box.innerHTML=S.active.map(id=>{let p=policy(id),keep=S.keep[id]!==false;return '<div class="continueRow"><div><b>'+p.icon+' '+p.name+'</b><div class="small">維持費 '+p.upkeep+'pt／年・継続効果は初年度の約25%</div></div><div class="seg"><button data-id="'+id+'" data-keep="1" class="'+(keep?'on':'')+'">続ける</button><button data-id="'+id+'" data-keep="0" class="'+(!keep?'stopOn':'')+'">やめる</button></div></div>'}).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{S.keep[b.dataset.id]=b.dataset.keep==='1';trimSelections();renderAll()})}
function renderPolicies(){let h=$('policyGrid'),limit=currentLimit();h.innerHTML='';P.forEach(p=>{if(p.id==='rest')return;let active=S.active.includes(p.id),sel=S.selected.includes(p.id),fit=localFit(p),full=totalPlanned()>=limit&&!sel&&!active,d=document.createElement('div');d.className='policy'+(sel?' selected':'')+(active?' activePolicy':'')+(full?' slotFull':'');let tags=adjustedEffects(p,fit).map(([k,v])=>'<span class="tag '+(v>=0?'plus':'minus')+'">'+M[k].n+' '+(v>0?'+':'')+v+'</span>').join('');let status=active?'<span class="activeBadge">継続判断は上で</span>':full?'<span class="activeBadge">今年の'+limit+'枠が埋まっています</span>':'';d.innerHTML='<span class="cost">'+p.cost+'pt</span>'+status+'<h3>'+p.icon+' '+p.name+'</h3><div class="small">'+p.desc+'</div><div class="effects">'+tags+'</div><div class="localFit"><b>今年の実効補正 ×'+fit.m.toFixed(2)+'</b><br>'+(fit.w.length?fit.w.join(' ／ '):'固有補正なし')+'</div>';if(!active&&!full)d.onclick=()=>toggle(p.id);h.appendChild(d)})}
function toggle(id){let p=policy(id),i=S.selected.indexOf(id);if(i>=0)S.selected.splice(i,1);else{if(totalPlanned()>=currentLimit())return;if(selectedCost()+p.cost>available())return alert('今年の予算が足りません。継続事業をやめると予算が戻る場合があります。');S.selected.push(id)}renderAll()}
function renderEvent(){$('yearEvent').textContent=S.event.text;let a=S.event.voices.slice();if(S.v.stay<42)a.push('町に住んでいても、平日はほとんど町外にいるよ。');if(S.v.equity<42)a.push('地区によって参加しやすさが違う気がする。');if(S.v.fatigue>62)a.push('活動は増えたけど、準備する人がもう限界かも。');$('voices').innerHTML=a.slice(0,4).map((x,i)=>'<div class="voice"><b>'+(i%2?'👩 住民':'🧑 住民')+'</b>'+x+'</div>').join('')}
function renderSelected(){let a=S.selected.map(policy),spent=selectedCost(),remain=Math.max(0,available()-spent),continued=continuedIds().length,total=totalPlanned(),limit=currentLimit(),left=slotsLeft();$('budget').textContent=remain;$('upkeepBox').innerHTML='<b>今年の施策枠 '+total+'/'+limit+'（継続 '+continued+'／新規 '+a.length+'）</b><br><span class="small">'+(S.year===1?'初年度は新規施策を最大2つまで。':'2年目以降は継続を含めて最大3つ。')+' 継続費 '+upkeep()+'pt。</span>';$('selectedSummary').innerHTML=a.length?'<b>新しく選択：</b>'+a.map(p=>p.icon+p.name).join(' ＋ ')+'<br><span class="small">新規費 '+spent+'pt／残り '+remain+'pt／あと'+left+'枠</span>':'<b>新規施策はまだありません。</b><br><span class="small">継続を含めて今年は'+total+'/'+limit+'枠を使用中です。</span>';let dock=$('runDock');let ready=S.year===1?total===2:(total>=2&&total<=limit);if(ready&&!S.resolved){dock.classList.add('show');$('dockTitle').textContent='今年の施策 '+total+'/'+limit;$('dockSummary').textContent=(continued?'継続'+continued+' ＋ ':'')+(a.length?'新規'+a.length:'新規0')+(left?'　あと'+left+'つ追加できます':'　枠をすべて使用');$('dockRun').textContent='この'+total+'施策で1年進める →'}else dock.classList.remove('show')}
function renderAll(){ensureYearContext();$('year').textContent=S.year;$('milestone').textContent=milestone();renderContinuations();renderSelected();renderEvent();renderPulse();renderMetrics();renderPolicies();window.dispatchEvent(new CustomEvent('machi:statechange'))}
function updateFocusStreak(ids){const focus=new Set();ids.forEach(id=>policy(id).focus.forEach(k=>focus.add(k)));['child','youth','senior','industry','tourism','connection','equity','stay'].forEach(k=>S.focusStreak[k]=focus.has(k)?(S.focusStreak[k]||0)+1:0)}
function runYear(){let total=totalPlanned(),limit=currentLimit();if(S.resolved||total<2||total>limit)return;if(S.year===1&&total!==2)return;S.resolved=true;$('runDock').classList.remove('show');let chosen=S.selected.map(policy),pl=plan(),delta={...pl.delta},reasons=[],continuedNow=continuedIds(),ids=continuedNow.concat(chosen.map(p=>p.id));if(Object.keys((S.event&&S.event.e)||{}).length)reasons.push('今年の地域状況：'+Object.entries(S.event.e).map(([k,v])=>M[k].n+(v>0?'+':'')+v).join('、'));continuedNow.forEach(id=>reasons.push('継続：'+policy(id).name+'（維持費'+policy(id).upkeep+'pt）'));S.active.filter(id=>S.keep[id]===false).forEach(id=>reasons.push('終了：'+policy(id).name+'（維持費と継続効果を停止）'));chosen.forEach(p=>{let fit=localFit(p);reasons.push(p.name+'：'+(fit.w.length?fit.w.join(' ／ '):'標準効果')+' → ×'+fit.m.toFixed(2))});let explain={};comboAdjust(explain,reasons,ids);opinionAdjust(explain,reasons,ids);biasAdjust(explain,reasons,ids);let surprise=pick(SURPRISE);Object.entries(surprise.e||{}).forEach(([k,v])=>delta[k]=(delta[k]||0)+v);if(surprise.budget)S.nextBudgetBonus+=surprise.budget;let before={...S.v};Object.entries(delta).forEach(([k,v])=>S.v[k]=clamp(S.v[k]+v));S.neglect=pl.nextNeglect;updateFocusStreak(ids);let nextActive=continuedNow.slice();chosen.forEach(p=>{if(p.upkeep&&!nextActive.includes(p.id))nextActive.push(p.id)});S.active=nextActive.slice(0,MAX_POLICIES);S.keep={};S.active.forEach(id=>S.keep[id]=true);let allNames=continuedNow.map(id=>'継続:'+policy(id).name).concat(chosen.map(p=>'新規:'+p.name));S.history.push({year:S.year,names:allNames,v:{...S.v}});let g=GOALS[S.goal];$('resultTitle').textContent=S.year+'年目の結果';$('surprise').textContent='予想外の出来事：'+surprise.text;$('changes').innerHTML=Object.keys(M).map(k=>{let d=S.v[k]-before[k],target=(k==='fatigue'?'≤':'≥')+g.t[k];return '<div class="change">'+M[k].i+' '+M[k].n+' <b class="'+(d>=0?'up':'down')+'">'+(d>0?'+':'')+d+'</b> → '+S.v[k]+' <span class="targetNote">（目標値: '+target+'）</span></div>'}).join('');$('reasons').innerHTML=reasons.map(x=>'・'+x).join('<br>');let a=[];if(S.v.acceptance<45)a.push('最近の施策、誰のためなのか分からないという声が増えている。');if(S.v.child>=70)a.push('子育ての選択肢が増えてきたと感じる。');if(S.v.equity<40)a.push('中心の地区は便利になったけど、うちの地区は置いていかれてる感じ。');if(S.v.fatigue>70)a.push('新しいことより、続け方を考えてほしい。');if(!a.length)a.push('少しずつ変わっているけど、次はどこに力を入れるか気になる。');$('afterVoices').innerHTML=a.map(x=>'<div class="voice">👤 '+x+'</div>').join('');$('result').classList.remove('hidden');renderHistory();$('result').scrollIntoView({behavior:'smooth',block:'start'});window.dispatchEvent(new CustomEvent('machi:statechange'))}
const HIST_KEYS=['connection','youth','child','senior','stay','industry','tourism','equity','acceptance','fatigue'];
function renderHistory(){$('history').innerHTML=S.history.map(h=>'<tr><td>'+h.year+'</td><td>'+h.names.join(' / ')+'</td>'+HIST_KEYS.map(k=>'<td>'+h.v[k]+'</td>').join('')+'</tr>').join('')}
function next(){if(S.year>=5)return finish();S.year++;S.selected=[];S.event=null;S.concerns=null;S.currentBudgetBonus=S.nextBudgetBonus;S.nextBudgetBonus=0;S.resolved=false;S.keep={};S.active.forEach(id=>S.keep[id]=true);$('result').classList.add('hidden');renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function metricProgress(k,target){let start=START[k],now=S.v[k];if(k==='fatigue'){if(start<=target){if(now<=target)return 1;return Math.max(0,1-(now-target)/Math.max(1,100-target))}return Math.max(0,Math.min(1,(start-now)/Math.max(1,start-target)))}if(target>start)return Math.max(0,Math.min(1,(now-start)/(target-start)));if(now>=target)return 1;return Math.max(0,Math.min(1,now/Math.max(1,target)))}
function achievementScore(){let g=GOALS[S.goal],primary=new Set(PRIMARY[S.goal]||[]),sum=0,weights=0;Object.entries(g.t).forEach(([k,t])=>{let w=primary.has(k)?4:1;sum+=metricProgress(k,t)*w;weights+=w});let score=Math.round(sum/weights*100);if(S.approach==='hybrid')score=Math.min(100,score+3);if(S.v.acceptance<45)score=Math.min(score,72);return score}
function finish(){let g=GOALS[S.goal],ach=achievementScore(),primary=PRIMARY[S.goal]||[];$('play').classList.add('hidden');$('ending').classList.remove('hidden');$('runDock').classList.remove('show');$('endingTitle').textContent=g.icon+' '+g.name+' × '+APPROACHES[S.approach].name;$('achievement').textContent=ach;$('endingLabel').textContent=ach>=90?'🏆 目標と納得感を両立した':ach>=78?'🌟 方向性が形になった':ach>=65?'🧭 成果と葛藤がはっきりした':'🧪 優先順位を組み直して再挑戦';$('scoreBreakdown').innerHTML='<b>この％の意味：</b>開始時点から目標へ進んだ度合いに加え、「'+g.name+'」の中心指標を重く評価しています。<br><span class="small">住民の納得感が45未満の場合は、他の数値が高くても総合評価に上限がかかります。</span>';let dif=Object.keys(M).filter(k=>k!=='fatigue').map(k=>({k,d:S.v[k]-START[k]})).sort((a,b)=>b.d-a.d);$('strengthReport').innerHTML=dif.slice(0,4).map(x=>'<li>'+M[x.k].n+'：'+START[x.k]+' → '+S.v[x.k]+'（'+(x.d>=0?'+':'')+x.d+'）</li>').join('');let c=[];Object.entries(g.t).forEach(([k,t])=>{let miss=k==='fatigue'?S.v[k]>t:S.v[k]<t;if(miss)c.push(M[k].n+'：現在'+S.v[k]+'／目標'+(k==='fatigue'?'≤':'≥')+t)});if(!c.length)c.push('目標値はすべて達成。次は「誰が負担したか」を考えてみよう。');$('challengeReport').innerHTML=c.slice(0,6).map(x=>'<li>'+x+'</li>').join('');$('endingQuestion').innerHTML='<b>最後の問い：</b>住民の声に応えた年、あえて応えなかった年、同じ分野へ投資し続けた年。その選択は誰の納得と、どんな未来につながりましたか。';window.scrollTo({top:0,behavior:'smooth'})}
function start(){let a=$('approachGrid').querySelector('.choice.active').dataset.k,g=$('goalGrid').querySelector('.choice.active').dataset.k;S={year:1,approach:a,goal:g,v:{...START},selected:[],active:[],keep:{},neglect:{},focusStreak:{},history:[],event:null,concerns:null,currentBudgetBonus:0,nextBudgetBonus:0,resolved:false};$('approachPill').textContent=APPROACHES[a].icon+' '+APPROACHES[a].name;$('goalPill').textContent=GOALS[g].icon+' '+GOALS[g].name;$('setup').classList.add('hidden');$('play').classList.remove('hidden');$('ending').classList.add('hidden');$('result').classList.add('hidden');renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function reset(){$('runDock').classList.remove('show');$('play').classList.add('hidden');$('ending').classList.add('hidden');$('setup').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
window.MACHI_V9={getState:()=>S,getPolicies:()=>P,getConcerns:()=>S?S.concerns:[],getFit:p=>S?localFit(p):{m:1,w:[]},getPlan:()=>S?plan():null,getGoal:()=>S?GOALS[S.goal]:null,getMetrics:()=>M};
renderApproaches();renderGoals();$('start').onclick=start;$('dockRun').onclick=runYear;$('nextYear').onclick=next;$('resetTop').onclick=reset;$('restart').onclick=reset;
})();