const SUPABASE_URL='https://gxbgqajehfutdudjofno.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6Imd4YmdxYWplaGZ1dGR1ZGpvZm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA3MTQzMDMsImV4cCI6MjEwNjI5MDMwM30.NGzny52SesudiM2D4-1xy74I0bj1DuCKcLBEQB50pQk';
const CONFIG_KEY='dagashi-register-store-v1';
let storeSecret='';
let state={store_name:'ここも駄菓子屋',products:[],sales:[],stock_moves:[]};
let cart={};
let currentView='register';
let pollTimer=null;

const $=id=>document.getElementById(id);
const yen=n=>'¥'+Number(n||0).toLocaleString('ja-JP');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const todayKey=v=>new Date(v).toLocaleDateString('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit'});
const fmtTime=v=>new Date(v).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});

function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function setBadge(mode,msg=''){const e=$('syncBadge');e.className='sync-badge '+(mode==='ok'?'ok':mode==='err'?'err':'');e.textContent=msg||(mode==='ok'?'クラウド接続済み':mode==='err'?'クラウド未接続':'接続中…')}
function saveSecret(){localStorage.setItem(CONFIG_KEY,storeSecret)}
function loadSecret(){const q=new URLSearchParams(location.search);const s=q.get('store');if(s){storeSecret=s.trim().toUpperCase();saveSecret();q.delete('store');history.replaceState(null,'',location.pathname+(q.toString()?'?'+q.toString():''));return}storeSecret=(localStorage.getItem(CONFIG_KEY)||'').trim().toUpperCase()}
async function rpc(name,args={}){let res;try{res=await fetch(SUPABASE_URL+'/rest/v1/rpc/'+encodeURIComponent(name),{method:'POST',cache:'no-store',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(args)})}catch{throw new Error('クラウドへ接続できません')}const txt=await res.text();let data=null;if(txt){try{data=JSON.parse(txt)}catch{data=txt}}if(!res.ok)throw new Error((data&&typeof data==='object'&&(data.message||data.details||data.hint))||('HTTP '+res.status));return data}
async function loadState(silent=false){if(!storeSecret){setBadge('err','店舗未接続');$('connectPanel').classList.remove('hidden');return false}try{const data=await rpc('dr_get_state',{p_secret:storeSecret});if(!data)throw new Error('店舗コードが違います');state=data;$('connectPanel').classList.add('hidden');setBadge('ok');renderAll();return true}catch(e){setBadge('err');$('connectPanel').classList.remove('hidden');$('connectError').textContent=e.message;$('connectError').classList.remove('hidden');if(!silent)toast(e.message);return false}}

function switchView(v){currentView=v;['register','stock','adjust','sales','products'].forEach(x=>$('view-'+x).classList.toggle('hidden',x!==v));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function productById(id){return state.products.find(p=>p.id===id)}
function cartTotals(){let count=0,total=0;for(const [id,q] of Object.entries(cart)){const p=productById(id);if(!p)continue;count+=q;total+=Number(p.sale_price)*q}return{count,total}}
function renderRegister(){const grid=$('productGrid');grid.innerHTML=state.products.filter(p=>p.active).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(p=>{const q=cart[p.id]||0;const out=p.stock<=0;const low=p.stock>0&&p.stock<=p.low_stock_threshold;return `<article class="product-card ${out?'soldout':''}"><div><div class="product-name">${esc(p.name)}</div><div class="product-meta">${esc(p.category)} ・ 在庫 <span class="${low?'low':''}">${p.stock}</span></div></div><div><div class="product-price">${yen(p.sale_price)}</div>${out?'<span class="pill out">売り切れ</span>':`<div class="qty-row"><button class="secondary" data-dec="${p.id}">−</button><b>${q}</b><button class="primary" data-inc="${p.id}">＋</button></div>`}</div></article>`}).join('')||'<div class="panel">商品がありません。</div>';grid.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{const p=productById(b.dataset.inc);const q=cart[p.id]||0;if(q>=p.stock){toast('在庫以上は選べません');return}cart[p.id]=q+1;renderRegister()});grid.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const id=b.dataset.dec;cart[id]=Math.max(0,(cart[id]||0)-1);renderRegister()});const t=cartTotals();$('cartCount').textContent=t.count+'点';$('cartTotal').textContent=yen(t.total);$('checkoutBtn').disabled=t.count===0;$('checkoutBtn').style.opacity=t.count===0?'.45':'1';updateChangePreview()}
function updateChangePreview(){const total=cartTotals().total;const received=Number($('receivedInput').value||0);$('changePreview').textContent=received?received>=total?'おつり：'+yen(received-total):'不足：'+yen(total-received):'おつり：—'}
async function checkout(){const items=Object.entries(cart).filter(([,q])=>q>0).map(([id,qty])=>({id,qty}));if(!items.length)return;const receivedRaw=$('receivedInput').value.trim();const received=receivedRaw===''?null:Number(receivedRaw);$('checkoutBtn').disabled=true;try{const r=await rpc('dr_checkout',{p_secret:storeSecret,p_items:items,p_received:received});cart={};$('receivedInput').value='';await loadState(true);toast('会計 '+r.sale_no+'：'+yen(r.total)+(r.change_due!==null?'／おつり '+yen(r.change_due):''))}catch(e){toast('会計できません：'+e.message);renderAll()}}

function renderStock(){const products=state.products;const totalUnits=products.reduce((s,p)=>s+Number(p.stock||0),0);const inventoryCost=products.reduce((s,p)=>s+Number(p.stock||0)*Number(p.cost_price||0),0);const low=products.filter(p=>p.stock>0&&p.stock<=p.low_stock_threshold).length;const out=products.filter(p=>p.stock<=0).length;$('stockSummary').innerHTML=metric('在庫点数',totalUnits+'点')+metric('在庫原価',yen(inventoryCost))+metric('残りわずか',low+'商品')+metric('売り切れ',out+'商品');$('stockList').innerHTML=products.map(p=>{const cls=p.stock<=0?'out':p.stock<=p.low_stock_threshold?'warn':'';const label=p.stock<=0?'売り切れ':p.stock<=p.low_stock_threshold?'残りわずか':'在庫あり';return `<div class="list-item"><div class="item-main"><div class="item-title">${esc(p.name)}</div><div class="muted small">${esc(p.category)}／仕入 ${yen(p.cost_price)}／売値 ${yen(p.sale_price)}</div></div><div><span class="pill ${cls}">${label}</span><div style="text-align:right;font-size:22px;font-weight:900;margin-top:6px">${p.stock}</div></div></div>`}).join('')}
function metric(label,value){return `<div class="metric"><span class="muted small">${label}</span><b>${value}</b></div>`}

function renderAdjust(){const sel=$('adjustProduct');const current=sel.value;sel.innerHTML=state.products.map(p=>`<option value="${p.id}">${esc(p.name)}（在庫 ${p.stock}）</option>`).join('');if(state.products.some(p=>p.id===current))sel.value=current;const nameById=Object.fromEntries(state.products.map(p=>[p.id,p.name]));$('moveList').innerHTML=(state.stock_moves||[]).slice(0,50).map(m=>{const labels={initial:'初期在庫',receive:'入荷',sale:'販売',adjust_in:'棚卸増',adjust_out:'棚卸減'};return `<div class="list-item"><div><div class="item-title">${esc(nameById[m.product_id]||'商品')}</div><div class="muted small">${fmtTime(m.created_at)} ${m.note?'／'+esc(m.note):''}</div></div><div style="font-weight:900;font-size:18px">${m.qty_delta>0?'+':''}${m.qty_delta}<div class="muted small">${labels[m.movement_type]||m.movement_type}</div></div></div>`}).join('')||'<div class="panel muted">履歴はまだありません。</div>'}
async function adjustStock(){const id=$('adjustProduct').value;const mode=$('adjustMode').value;const qty=Number($('adjustQty').value);const note=$('adjustNote').value.trim();if(!id||!Number.isFinite(qty)||qty<0){toast('数量を確認してください');return}try{await rpc('dr_adjust_stock',{p_secret:storeSecret,p_product_id:id,p_mode:mode,p_quantity:qty,p_note:note||null});$('adjustQty').value='';$('adjustNote').value='';await loadState(true);toast('在庫を更新しました')}catch(e){toast('在庫を更新できません：'+e.message)}}

function todaySales(){const today=todayKey(new Date());return (state.sales||[]).filter(s=>todayKey(s.created_at)===today)}
function renderSales(){const sales=todaySales();const revenue=sales.reduce((s,x)=>s+Number(x.total||0),0);const cost=sales.reduce((s,x)=>s+Number(x.cost_total||0),0);const profit=revenue-cost;const qty=sales.reduce((s,x)=>s+(x.items||[]).reduce((a,i)=>a+Number(i.qty||0),0),0);const margin=revenue?profit/revenue*100:0;$('salesMetrics').innerHTML=metric('今日の売上',yen(revenue))+metric('売上原価',yen(cost))+metric('粗利益',yen(profit))+metric('粗利率',margin.toFixed(1)+'%');const by={};for(const sale of sales){for(const i of sale.items||[]){const k=i.product_id||i.product_name;if(!by[k])by[k]={name:i.product_name,qty:0,revenue:0,cost:0};by[k].qty+=Number(i.qty);by[k].revenue+=Number(i.line_total);by[k].cost+=Number(i.line_cost)}}$('productPerformance').innerHTML=Object.values(by).sort((a,b)=>b.qty-a.qty).map(x=>`<div class="performance-row"><div><b>${esc(x.name)}</b></div><div>${x.qty}点</div><div>売上 ${yen(x.revenue)}</div><div>原価 ${yen(x.cost)}</div><div><b>粗利 ${yen(x.revenue-x.cost)}</b></div></div>`).join('')||'<div class="muted">今日の販売はまだありません。</div>';$('salesList').innerHTML=(state.sales||[]).slice(0,30).map(s=>`<div class="list-item"><div><div class="item-title">会計 #${s.sale_no}</div><div class="muted small">${fmtTime(s.created_at)}／${(s.items||[]).reduce((a,i)=>a+Number(i.qty),0)}点</div></div><div style="text-align:right"><b>${yen(s.total)}</b><div class="muted small">粗利 ${yen(s.gross_profit)}</div></div></div>`).join('')||'<div class="panel muted">会計履歴はまだありません。</div>'}
function exportCsv(){const rows=[['会計番号','日時','売上','原価','粗利益','販売点数']];for(const s of state.sales||[])rows.push([s.sale_no,new Date(s.created_at).toLocaleString('ja-JP'),s.total,s.cost_total,s.gross_profit,(s.items||[]).reduce((a,i)=>a+Number(i.qty),0)]);const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dagashi-sales-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function renderProductsAdmin(){$('productAdminList').innerHTML=state.products.map(p=>`<div class="list-item"><div><div class="item-title">${esc(p.name)}</div><div class="muted small">${esc(p.category)}／仕入 ${yen(p.cost_price)}／売値 ${yen(p.sale_price)}／在庫 ${p.stock}</div></div><div class="row"><span class="pill">${p.active?'販売中':'停止'}</span><button class="secondary small" data-edit="${p.id}">編集</button></div></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit))}
function openProduct(id=null){const p=id?productById(id):null;$('productDialogTitle').textContent=p?'商品を編集':'商品を追加';$('productId').value=p?.id||'';$('productName').value=p?.name||'';$('productCategory').value=p?.category||'その他';$('productCost').value=p?.cost_price??0;$('productSale').value=p?.sale_price??0;$('productLow').value=p?.low_stock_threshold??5;$('productActive').checked=p?.active!==false;$('productInitialStock').value=0;$('initialStockLabel').classList.toggle('hidden',!!p);$('productDialog').showModal()}
async function saveProduct(){const id=$('productId').value||null;const name=$('productName').value.trim();if(!name){toast('商品名を入力してください');return}try{await rpc('dr_upsert_product',{p_secret:storeSecret,p_product_id:id,p_name:name,p_category:$('productCategory').value.trim()||'その他',p_cost_price:Number($('productCost').value||0),p_sale_price:Number($('productSale').value||0),p_low_stock_threshold:Number($('productLow').value||0),p_active:$('productActive').checked,p_initial_stock:Number($('productInitialStock').value||0)});$('productDialog').close();await loadState(true);toast(id?'商品を更新しました':'商品を追加しました')}catch(e){toast('保存できません：'+e.message)}}

function renderAll(){if(currentView==='register')renderRegister();if(currentView==='stock')renderStock();if(currentView==='adjust')renderAdjust();if(currentView==='sales')renderSales();if(currentView==='products')renderProductsAdmin()}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>loadState(true),3000)}

loadSecret();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$('receivedInput').addEventListener('input',updateChangePreview);
$('checkoutBtn').onclick=checkout;$('clearCartBtn').onclick=()=>{cart={};renderRegister()};$('adjustBtn').onclick=adjustStock;$('newProductBtn').onclick=()=>openProduct();$('saveProductBtn').onclick=saveProduct;$('exportBtn').onclick=exportCsv;$('connectBtn').onclick=async()=>{storeSecret=$('storeCodeInput').value.trim().toUpperCase();saveSecret();if(await loadState(false))startPolling()};
loadState(false).then(ok=>{if(ok)startPolling()});
renderAll();