(function(){
'use strict';
var $=id=>document.getElementById(id);var state=null;
var DISTRICTS=[['津嘉山',11053],['宮平',7462],['兼城',5692],['新川',2966],['与那覇',2514],['本部',1804],['照屋',1618],['山川',1218],['喜屋武',1220],['宮城',1118],['大名',1059],['神里',913],['南風原第二団地',601],['兼本ハイツ',559],['南風原第一団地',515],['北丘ハイツ',330],['宮平ハイツ',292],['東新川',279],['兼平',189]];
var META={connection:{name:'地域のつながり',icon:'🤝'},youth:{name:'若者の参加',icon:'🧑‍🎓'},child:{name:'子育て・子ども',icon:'👶'},senior:{name:'高齢者の参加',icon:'👴'},tourism:{name:'観光・交流人口',icon:'🏝️'},info:{name:'情報の届きやすさ',icon:'📣'},fatigue:{name:'担い手のつかれ',icon:'🔋'}};
var GOALS={
youth:{icon:'🌱',name:'若者が元気なまち',desc:'若者が地域でやってみたいことを形にでき、役割や居場所があるまち。',targets:{connection:65,youth:75,child:60,senior:55,tourism:45,info:65,fatigue:45}},
child:{icon:'👶',name:'子育てしやすいまち',desc:'子どもと保護者が孤立しにくく、安心して過ごし、声を届けられるまち。',targets:{connection:72,youth:60,child:80,senior:58,tourism:35,info:72,fatigue:45}},
senior:{icon:'👴',name:'高齢者が活発なまち',desc:'高齢者が支えられるだけでなく、地域で役割をもち、人と会えるまち。',targets:{connection:72,youth:52,child:55,senior:80,tourism:35,info:65,fatigue:45}},
tourism:{icon:'🏝️',name:'観光の聖地',desc:'地域資源を生かして人が訪れ、地域経済や交流が広がるまち。暮らしとの両立も必要。',targets:{connection:60,youth:62,child:52,senior:52,tourism:82,info:75,fatigue:55}},
connected:{icon:'🤝',name:'つながりの強いまち',desc:'世代や立場を越えて、知り合い・情報・参加の入口があるまち。',targets:{connection:82,youth:62,child:65,senior:68,tourism:45,info:78,fatigue:45}},
learning:{icon:'📚',name:'学び続けるまち',desc:'公民館や地域の人材を生かし、子どもから大人まで学び合えるまち。',targets:{connection:72,youth:68,child:65,senior:65,tourism:42,info:70,fatigue:45}}
};
var POLICIES=[
{id:'line',icon:'📱',name:'地域情報LINEをつくる',cost:18,desc:'自治会・公民館・居場所・イベント情報を一つに集める。',e:{info:10,connection:3,fatigue:2}},
{id:'paper',icon:'📰',name:'紙の地域だよりを全戸へ',cost:16,desc:'SNSを使わない人にも地域情報が届くようにする。',e:{info:8,senior:4,connection:2,fatigue:2}},
{id:'youthCouncil',icon:'🧑‍🎓',name:'若者まちづくり会議',cost:24,desc:'中高生・大学生・若者が企画と予算の使い方に関われる場をつくる。',e:{youth:11,connection:4,info:2,fatigue:3}},
{id:'childPlace',icon:'🏠',name:'子どもと保護者の居場所',cost:28,desc:'予約なしでも立ち寄れ、親同士・子ども同士がつながれる場を支える。',e:{child:12,connection:6,youth:2,fatigue:3}},
{id:'seniorRole',icon:'🧓',name:'高齢者の「役割」プロジェクト',cost:20,desc:'見守り、昔遊び、料理、地域史など、得意を地域で生かせる仕組みをつくる。',e:{senior:11,connection:6,child:2,fatigue:2}},
{id:'multiGen',icon:'🍲',name:'多世代の小さな交流会',cost:14,desc:'大イベントではなく、各地区で少人数の食事会・遊び・おしゃべりを続ける。',e:{connection:9,senior:4,child:4,youth:3,fatigue:2}},
{id:'festival',icon:'🎪',name:'大規模まちフェス',cost:36,desc:'町外からも人を呼ぶ大きなイベント。注目は集まるが運営負担も大きい。',e:{tourism:13,info:7,connection:3,fatigue:10}},
{id:'localTour',icon:'🗺️',name:'地域資源まち歩き',cost:18,desc:'歴史・文化・店・人をつなぐ小さなツアーを住民とつくる。',e:{tourism:8,connection:5,youth:3,senior:3,fatigue:2}},
{id:'coordinator',icon:'🧭',name:'地域コーディネーターを配置',cost:32,desc:'活動者同士をつなぎ、相談・広報・役割分担を支える。',e:{connection:7,info:5,fatigue:-8,youth:2,child:2,senior:2}},
{id:'microgrant',icon:'💡',name:'住民の小さな挑戦に助成',cost:26,desc:'1〜5万円程度の小規模企画を住民自身が試せる仕組みをつくる。',e:{youth:6,connection:6,tourism:3,child:2,fatigue:3}},
{id:'openHall',icon:'🏫',name:'公民館を「使いやすい場」に',cost:22,desc:'空き時間・予約方法・利用ルールを見直し、地域活動の入口を広げる。',e:{connection:7,youth:4,senior:5,child:4,info:3,fatigue:1}},
{id:'learning',icon:'📚',name:'地域の学び合い講座',cost:18,desc:'住民が先生にも学ぶ人にもなる、小さな講座を各地区で実施する。',e:{connection:6,youth:4,senior:5,child:3,info:2,fatigue:2}}
];
var YEAR_EVENTS=[
{id:'movein',text:'🏠 新しい住民が増え、地域情報を知らない人が目立っています。',effect:{connection:-2,info:-2},voice:['引っ越してきたばかりで、地域のことがよく分からない。','自治会に入らなくても情報が分かると助かる。']},
{id:'heat',text:'☀️ 暑さが厳しい年。屋外イベントや高齢者の外出に負担が出ています。',effect:{senior:-3,fatigue:2},voice:['暑い日は外に出るのが大変さぁ。','集まるなら涼しい場所がいいね。']},
{id:'buzz',text:'📸 SNSで町の文化やグルメが少し話題になりました。',effect:{tourism:4,info:2},voice:['町外の友だちが南風原に来てみたいって。','観光客だけじゃなく、住民も楽しめるといいな。']},
{id:'leaders',text:'😵 いくつかの地域活動で「いつも同じ人が運営している」という声が出ています。',effect:{fatigue:5,connection:-1},voice:['また同じメンバーで準備かぁ…。','手伝いたいけど、何をすればいいのか分からない。']},
{id:'school',text:'🏫 学校と地域の連携を考えたいという声が増えています。',effect:{child:2,youth:1},voice:['学校の外でも地域の大人と会えると面白そう。','子どもが参加できる企画をもっと知りたい。']},
{id:'quiet',text:'🌿 大きな変化はない年。だからこそ、何を積み上げるかが問われます。',effect:{},voice:['派手なイベントがなくても、続くものがあるといいね。','顔の見える関係が少しずつ増えるといいな。']}
];
function clamp(v){return Math.max(0,Math.min(100,Math.round(v)))}function pick(a){return a[Math.floor(Math.random()*a.length)]}function fmt(n){return Math.round(n).toLocaleString('ja-JP')}
function renderDistricts(){$('districts').innerHTML=DISTRICTS.map(d=>'<div class="district"><b>'+d[0]+'</b>'+fmt(d[1])+'人</div>').join('')}
function renderGoals(){var host=$('goalChoices');host.innerHTML='';Object.keys(GOALS).forEach((k,i)=>{var g=GOALS[k],d=document.createElement('div');d.className='choice'+(i===0?' active':'');d.dataset.goal=k;d.innerHTML='<b>'+g.icon+' '+g.name+'</b><span class="small">'+g.desc+'</span>';d.onclick=function(){host.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));d.classList.add('active')};host.appendChild(d)})}
function targetLabel(k,v){return META[k].icon+' '+META[k].name+' '+(k==='fatigue'?'≤':'≥')+v}
function renderGoalStrip(){var g=GOALS[state.goal];$('goalStrip').innerHTML=Object.entries(g.targets).map(([k,v])=>'<span class="pill">'+targetLabel(k,v)+'</span>').join('')}
function renderIndicators(){var host=$('indicators');host.innerHTML='';Object.keys(META).forEach(k=>{var m=META[k],v=state.v[k],d=document.createElement('div');d.className='metric'+(k==='fatigue'?' fatigue':'');d.innerHTML='<div class="name">'+m.icon+' '+m.name+'</div><b>'+v+'</b><div class="bar"><span style="width:'+v+'%"></span></div>';host.appendChild(d)})}
function eventForYear(){return pick(YEAR_EVENTS)}
function milestone(){var y=state.year;return y===1?'🌱 1年目。まずは「入口」をつくろう。':y===3?'🏁 3年目・折り返し。数字だけでなく、住民の声も見直そう。':y===5?'🏆 最終年。目標に届くことと、無理をしすぎないことの両方を考えよう。':'あと'+(6-y)+'年。前の年の結果を次の作戦に生かそう。'}
function contextText(){var g=GOALS[state.goal];return '<b>目標：</b>'+g.icon+' '+g.name+'<br><span class="small">今年は施策を最大2つ。予算を残してもOKです。活動を増やしすぎると「担い手のつかれ」が上がる場合があります。</span>'}
function renderBeforeVoices(){var base=state.event.voice.slice();var extra=[];if(state.v.youth<55)extra.push('若い人が地域に関われる入口が少ない気がする。');if(state.v.info<55)extra.push('イベント、終わってから知ったよ。');if(state.v.connection<55)extra.push('近所に知り合いはいるけど、一緒に何かする感じではないかな。');if(state.v.fatigue>55)extra.push('活動は大事だけど、準備する人が少なすぎるよ。');var all=base.concat(extra).slice(0,4);$('voicesBefore').innerHTML=all.map((x,i)=>'<div class="voice"><b>'+(i%2?'👩 住民':'🧑 住民')+'</b>'+x+'</div>').join('')}
function renderPolicies(){var host=$('policyGrid');host.innerHTML='';POLICIES.forEach(p=>{var d=document.createElement('div');d.className='policy'+(state.selected.includes(p.id)?' selected':'');d.dataset.id=p.id;var tags=Object.entries(p.e).map(([k,v])=>'<span class="tag '+(v>=0?'plus':'minus')+'">'+META[k].name+' '+(v>0?'+':'')+v+'</span>').join('');d.innerHTML='<span class="cost">'+p.cost+'pt</span><h3>'+p.icon+' '+p.name+'</h3><div class="small">'+p.desc+'</div><div class="effects">'+tags+'</div>';d.onclick=()=>togglePolicy(p.id);host.appendChild(d)})}
function togglePolicy(id){if(state.locked)return;var idx=state.selected.indexOf(id);if(idx>=0)state.selected.splice(idx,1);else{if(state.selected.length>=2)return alert('1年に選べる施策は2つまでです。');var p=POLICIES.find(x=>x.id===id),spent=state.selected.reduce((a,x)=>a+POLICIES.find(p=>p.id===x).cost,0);if(spent+p.cost>state.budget)return alert('今年の予算が足りません。');state.selected.push(id)}renderPolicies();renderSelected()}
function renderSelected(){var arr=state.selected.map(id=>POLICIES.find(x=>x.id===id)),spent=arr.reduce((a,p)=>a+p.cost,0);$('budget').textContent=state.budget-spent;$('selectedSummary').innerHTML=arr.length?'<b>選択中：</b>'+arr.map(p=>p.icon+' '+p.name).join(' ＋ ')+'<br><span class="small">使用 '+spent+'pt／残り '+(state.budget-spent)+'pt</span>':'まだ施策を選んでいません。';$('runYear').disabled=state.locked}
function renderPlay(){$('goalPill').textContent=GOALS[state.goal].icon+' '+GOALS[state.goal].name;$('year').textContent=state.year;$('milestone').textContent=milestone();$('yearContext').innerHTML=contextText();$('eventPreview').textContent=state.event.text;renderGoalStrip();renderIndicators();renderBeforeVoices();renderPolicies();renderSelected()}
function synergy(delta,chosen){if(chosen.includes('line')&&chosen.includes('paper')){delta.info=(delta.info||0)+4;delta.connection=(delta.connection||0)+2}if(chosen.includes('youthCouncil')&&chosen.includes('microgrant')){delta.youth=(delta.youth||0)+5;delta.connection=(delta.connection||0)+2}if(chosen.includes('coordinator'))delta.fatigue=(delta.fatigue||0)-Math.max(1,chosen.length*2);if(chosen.includes('festival')&&!chosen.includes('coordinator'))delta.fatigue=(delta.fatigue||0)+3;if(chosen.includes('multiGen')&&chosen.includes('seniorRole'))delta.senior=(delta.senior||0)+4;if(chosen.includes('openHall')&&chosen.includes('learning')){delta.connection=(delta.connection||0)+3;delta.youth=(delta.youth||0)+2}}
function runYear(){if(state.locked)return;state.locked=true;var before=JSON.parse(JSON.stringify(state.v)),delta={};Object.entries(state.event.effect||{}).forEach(([k,v])=>delta[k]=(delta[k]||0)+v);state.selected.forEach(id=>{var p=POLICIES.find(x=>x.id===id);Object.entries(p.e).forEach(([k,v])=>delta[k]=(delta[k]||0)+v)});synergy(delta,state.selected);Object.entries(delta).forEach(([k,v])=>state.v[k]=clamp(before[k]+v));var chosenNames=state.selected.map(id=>POLICIES.find(x=>x.id===id).name);var changeText=Object.keys(META).map(k=>{var diff=state.v[k]-before[k];if(!diff)return '';return META[k].icon+' '+META[k].name+' '+(diff>0?'+':'')+diff}).filter(Boolean);$('changes').innerHTML=changeText.length?changeText.join('<br>'):'大きな数値変化はありませんでした。';$('eventResult').textContent=state.event.text;var voices=[];if(state.v.fatigue>65)voices.push('やることが増えて、運営する人がかなり疲れてきてるよ。');if((delta.info||0)>=8)voices.push('前より地域の情報が見つけやすくなった！');if((delta.youth||0)>=8)voices.push('自分たちのアイデアを出せる場ができて面白い。');if((delta.child||0)>=8)voices.push('子どもと一緒に行ける場所が増えて助かる。');if((delta.senior||0)>=8)voices.push('「来てください」じゃなくて、私にも役割があるのがうれしい。');if((delta.tourism||0)>=8)voices.push('町外から来る人が増えたね。でも住んでいる人の暮らしも大事にしたい。');if(!voices.length)voices.push('少しずつ変わってきた気がする。続く仕組みになるといいな。');$('voicesAfter').innerHTML=voices.slice(0,4).map((x,i)=>'<div class="voice"><b>'+(i%2?'👴 住民':'🧑‍🎓 住民')+'</b>'+x+'</div>').join('');state.history.push({year:state.year,policies:chosenNames.length?chosenNames.join('・'):'施策なし',v:JSON.parse(JSON.stringify(state.v))});renderHistory();$('resultTitle').textContent=state.year+'年目の結果';$('yearResult').classList.remove('hidden');$('runYear').disabled=true;renderIndicators();$('yearResult').scrollIntoView({behavior:'smooth',block:'start'})}
function renderHistory(){var h=$('historyBody');if(!state.history.length){h.innerHTML='<tr><td colspan="8">まだ記録はありません</td></tr>';return}h.innerHTML=state.history.map(x=>'<tr><td>'+x.year+'年</td><td>'+x.policies+'</td><td>'+x.v.connection+'</td><td>'+x.v.youth+'</td><td>'+x.v.child+'</td><td>'+x.v.senior+'</td><td>'+x.v.tourism+'</td><td>'+x.v.fatigue+'</td></tr>').join('')}
function nextYear(){if(state.year>=5){finish();return}state.year++;state.selected=[];state.locked=false;state.event=eventForYear();$('yearResult').classList.add('hidden');renderPlay();window.scrollTo({top:0,behavior:'smooth'})}
function achieved(k,current,target){return k==='fatigue'?current<=target:current>=target}function ratio(k,current,target){if(k==='fatigue'){if(current<=target)return 1;return Math.max(0,1-(current-target)/55)}return Math.min(1,current/target)}
function finish(){$('play').classList.add('hidden');$('ending').classList.remove('hidden');var g=GOALS[state.goal];$('endingGoal').textContent=g.icon+' '+g.name;var vals=Object.keys(g.targets).map(k=>ratio(k,state.v[k],g.targets[k]));var pct=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*100);$('achievement').textContent=pct;$('endingLabel').textContent=pct>=90?'🏆 かなり近づいた！':pct>=75?'🌟 方向は見えてきた':pct>=60?'🌱 まだ伸ばせる':'🧭 作戦を組み直そう';$('goalReport').innerHTML=Object.entries(g.targets).map(([k,t])=>'<li>'+(achieved(k,state.v[k],t)?'✅':'△')+' '+META[k].name+'：'+state.v[k]+'（目標 '+(k==='fatigue'?'≤':'≥')+t+'）</li>').join('');var notes=[];if(state.v.fatigue>60)notes.push('活動は増えましたが、担い手のつかれが高めです。誰が支えるか、役割を分散する仕組みが必要そうです。');else notes.push('担い手のつかれは比較的抑えられました。継続できる運営に近づいています。');var highest=Object.keys(META).filter(k=>k!=='fatigue').sort((a,b)=>state.v[b]-state.v[a])[0];var lowest=Object.keys(META).filter(k=>k!=='fatigue').sort((a,b)=>state.v[a]-state.v[b])[0];notes.push('もっとも高くなった強みは「'+META[highest].name+'」です。');notes.push('次に考えたい弱点は「'+META[lowest].name+'」です。');var festivalYears=state.history.filter(x=>x.policies.indexOf('大規模まちフェス')>=0).length;if(festivalYears>=2)notes.push('大規模イベントを複数年実施しました。注目は集まりますが、日常のつながりが十分かも振り返ってみよう。');$('analysisReport').innerHTML=notes.map(x=>'<li>'+x+'</li>').join('');$('endingQuestion').innerHTML='<b>最後の問い</b><br>目標に近づいたとして、このまちは「誰にとって」よくなったでしょうか？ 数字に表れにくい人や、参加できなかった人はいませんでしたか？';window.scrollTo({top:0,behavior:'smooth'})}
function start(){var active=document.querySelector('#goalChoices .choice.active');var goal=active?active.dataset.goal:'youth';state={goal:goal,year:1,budget:100,selected:[],locked:false,event:null,history:[],v:{connection:52,youth:46,child:58,senior:55,tourism:38,info:48,fatigue:34}};state.event=eventForYear();$('setup').classList.add('hidden');$('ending').classList.add('hidden');$('play').classList.remove('hidden');$('yearResult').classList.add('hidden');renderHistory();renderPlay();window.scrollTo({top:0,behavior:'smooth'})}
function reset(){state=null;$('play').classList.add('hidden');$('ending').classList.add('hidden');$('setup').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
$('start').onclick=start;$('runYear').onclick=runYear;$('nextYear').onclick=nextYear;$('resetTop').onclick=reset;$('restart').onclick=reset;renderDistricts();renderGoals();
})();