(function(){
'use strict';
const D=window.GAME_DATA,$=id=>document.getElementById(id),{M,START,APPROACHES,GOALS,POLICIES:P,EVENTS,SURPRISE}=D;let S=null;
const clamp=v=>Math.max(0,Math.min(100,Math.round(v))),pick=a=>a[Math.floor(Math.random()*a.length)];
function approachBonus(p){let m=1,w=[];if(S.approach==='repair'&&(p.tags.includes('repair')||p.tags.includes('jobs')||p.tags.includes('distributed')||p.tags.includes('flexible'))){m*=1.12;w.push('課題解決方針 +12%')}if(S.approach==='strength'&&(p.tags.includes('strength')||p.tags.includes('business')||p.tags.includes('welfare')||p.tags.includes('child'))){m*=1.12;w.push('強み活用方針 +12%')}return{m,w}}
function localFit(p){let m=1,w=[];if(p.tags.includes('child')){m*=1.15;w.push('0〜14歳20.3% → 子ども施策+15%')}if(p.tags.includes('daytime')){m*=.78;w.push('町外通勤通学67.6% → 日中型−22%')}if(p.tags.includes('flexible')){m*=1.15;w.push('町外通勤通学67.6% → 夜・オンライン+15%')}if(p.tags.includes('jobs')){m*=1.15;w.push('町外通勤通学67.6% → 町内仕事施策+15%')}if(p.tags.includes('business')){m*=1.12;w.push('1,441事業所 → 事業者連携+12%')}if(p.tags.includes('welfare')){m*=1.10;w.push('医療・福祉4,338人 → 連携+10%')}if(p.tags.includes('mobility')){m*=1.10;w.push('社会増+412人 → 転入者施策+10%')}if(p.tags.includes('distributed')){m*=1.12;w.push('地区規模差 → 分散型+12%')}let a=approachBonus(p);m*=a.m;w=w.concat(a.w);if(S.v.fatigue>=80){m*=.62;w.push('担い手疲労80+ → 効果−38%')}else if(S.v.fatigue>=65){m*=.78;w.push('担い手疲労65+ → 効果−22%')}return{m,w}}
function renderApproaches(){let h=$('approachGrid');Object.entries(APPROACHES).forEach(([k,a],i)=>{let d=document.createElement('div');d.className='choice'+(i===2?' active':'');d.dataset.k=k;d.innerHTML='<b>'+a.icon+' '+a.name+'</b><span class="small">'+a.desc+'</span><div class="rule">'+a.bonus+'</div>';d.onclick=()=>{h.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));d.classList.add('active')};h.appendChild(d)})}
function renderGoals(){let h=$('goalGrid');Object.entries(GOALS).forEach(([k,g],i)=>{let d=document.createElement('div');d.className='choice'+(i===0?' active':'');d.dataset.k=k;let main=Object.entries(g.t).filter(([x])=>x!=='fatigue').sort((a,b)=>b[1]-a[1]).slice(0,3).map(([x,v])=>M[x].n+' '+v).join(' / ');d.innerHTML='<b>'+g.icon+' '+g.name+'</b><span class="small">'+main+'</span>';d.onclick=()=>{h.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));d.classList.add('active')};h.appendChild(d)})}
function upkeep(){return S.active.reduce((a,id)=>a+(P.find(x=>x.id===id).upkeep||0),0)}function available(){return Math.max(0,72+S.currentBudgetBonus-upkeep())}
function milestone(){return S.year===1?'🌱 1年目：同じデータでも「課題」と「強み」で作戦が変わる。':S.year===3?'🏁 3年目：折り返し。伸ばした分野と置き去りにした分野を確認。':S.year===5?'🏆 最終年：目標だけでなく、何を犠牲にしたかも見られます。':'あと'+(6-S.year)+'年。前の年の副作用を次の判断へ。'}
function renderMetrics(){let h=$('metricGrid'),g=GOALS[S.goal];h.innerHTML='';Object.entries(M).forEach(([k,m])=>{let v=S.v[k],t=g.t[k],ok=k==='fatigue'?v<=t:v>=t,d=document.createElement('div');d.className='metric'+(k==='fatigue'?' fatigue':'');d.innerHTML='<div class="name">'+m.i+' '+m.n+'</div><b>'+v+'</b><div class="bar"><span style="width:'+v+'%"></span></div><div class="goalLine '+(ok?'ok':'')+'">目標 '+(k==='fatigue'?'≤':'≥')+t+(ok?' ✓':'')+'</div>';h.appendChild(d)})}
function adjustedEffects(p,fit){return Object.entries(p.e).map(([k,v])=>[k,k==='fatigue'?v:Math.round(v*fit.m)])}
function renderPolicies(){let h=$('policyGrid');h.innerHTML='';P.forEach(p=>{let active=S.active.includes(p.id),sel=S.selected.includes(p.id),fit=localFit(p),d=document.createElement('div');d.className='policy'+(sel?' selected':'')+(active&&p.upkeep?' locked':'');let tags=adjustedEffects(p,fit).map(([k,v])=>'<span class="tag '+(v>=0?'plus':'minus')+'">'+M[k].n+' '+(v>0?'+':'')+v+'</span>').join('');d.innerHTML='<span class="cost">'+(active&&p.upkeep?'継続 '+p.upkeep+'pt/年':p.cost+'pt')+'</span><h3>'+p.icon+' '+p.name+'</h3><div class="small">'+p.desc+'</div><div class="effects">'+tags+'</div><div class="localFit"><b>南風原補正 ×'+fit.m.toFixed(2)+'</b><br>'+(fit.w.length?fit.w.join(' ／ '):'この施策への固有補正なし')+'</div>';if(!(active&&p.upkeep))d.onclick=()=>toggle(p.id);h.appendChild(d)})}
function toggle(id){let p=P.find(x=>x.id===id),i=S.selected.indexOf(id);if(i>=0)S.selected.splice(i,1);else{if(S.selected.length>=2)return alert('1年に選べる施策は2つまでです。');if(p.id==='rest'&&S.selected.length)return alert('「休む」は他の施策と同時に選べません。');if(S.selected.includes('rest'))return alert('「休む」を外してから選んでください。');let spent=S.selected.reduce((a,x)=>a+P.find(q=>q.id===x).cost,0);if(spent+p.cost>available())return alert('今年の予算が足りません。');S.selected.push(id)}renderAll()}
function renderEvent(){S.event=S.event||pick(EVENTS);$('yearEvent').textContent=S.event.text;let a=S.event.voices.slice();if(S.v.stay<42)a.push('町に住んでいても、平日はほとんど町外にいるよ。');if(S.v.equity<42)a.push('地区によって参加しやすさが違う気がする。');if(S.v.fatigue>62)a.push('活動は増えたけど、準備する人がもう限界かも。');$('voices').innerHTML=a.slice(0,4).map((x,i)=>'<div class="voice"><b>'+(i%2?'👩 住民':'🧑 住民')+'</b>'+x+'</div>').join('')}
function renderSelected(){let a=S.selected.map(id=>P.find(x=>x.id===id)),spent=a.reduce((n,p)=>n+p.cost,0);$('budget').textContent=Math.max(0,available()-spent);$('upkeepBox').innerHTML=S.active.length?'<b>継続費 '+upkeep()+'pt</b><br><span class="small">'+S.active.map(id=>{let p=P.find(x=>x.id===id);return p.icon+p.name+' '+p.upkeep+'pt'}).join(' ／ ')+'</span>':'<b>継続費 0pt</b><br><span class="small">まだ継続事業はありません。</span>';$('selectedSummary').innerHTML=a.length?'<b>今年選ぶ：</b>'+a.map(p=>p.icon+p.name).join(' ＋ ')+'<br><span class="small">新規費 '+spent+'pt</span>':'まだ施策を選んでいません。何も選ばず進むこともできます。'}
function renderAll(){$('year').textContent=S.year;$('milestone').textContent=milestone();renderMetrics();renderSelected();renderPolicies();renderEvent()}
function neglect(delta,focus,reasons){const base={youth:1,child:2,senior:1,stay:2,industry:1,tourism:1,equity:2};Object.entries(base).forEach(([k,b])=>{if(focus.has(k)){S.neglect[k]=0;return}S.neglect[k]=(S.neglect[k]||0)+1;let loss=b+Math.max(0,S.neglect[k]-1);delta[k]=(delta[k]||0)-loss;reasons.push(M[k].n+'を'+S.neglect[k]+'年後回し → -'+loss)})}
function runYear(){let chosen=S.selected.map(id=>P.find(x=>x.id===id)),delta={},reasons=[],focus=new Set();Object.entries(S.event.e||{}).forEach(([k,v])=>delta[k]=(delta[k]||0)+v);if(Object.keys(S.event.e||{}).length)reasons.push('今年の地域状況：'+Object.entries(S.event.e).map(([k,v])=>M[k].n+(v>0?'+':'')+v).join('、'));
S.active.forEach(id=>{let p=P.find(x=>x.id===id);p.focus.forEach(x=>focus.add(x));Object.entries(p.e).forEach(([k,v])=>{if(k==='fatigue'){delta[k]=(delta[k]||0)+Math.max(0,Math.round(v*.25))}else if(v>0){delta[k]=(delta[k]||0)+Math.max(1,Math.round(v*.25))}})});
chosen.forEach(p=>{let fit=localFit(p);p.focus.forEach(x=>focus.add(x));adjustedEffects(p,fit).forEach(([k,v])=>delta[k]=(delta[k]||0)+v);reasons.push(p.name+'：'+(fit.w.length?fit.w.join(' ／ '):'標準効果')+' → ×'+fit.m.toFixed(2));if(p.upkeep&&!S.active.includes(p.id))S.active.push(p.id)});
neglect(delta,focus,reasons);let surprise=pick(SURPRISE);Object.entries(surprise.e||{}).forEach(([k,v])=>delta[k]=(delta[k]||0)+v);if(surprise.budget)S.nextBudgetBonus+=surprise.budget;let before={...S.v};Object.entries(delta).forEach(([k,v])=>S.v[k]=clamp(S.v[k]+v));S.history.push({year:S.year,names:chosen.map(p=>p.name),v:{...S.v}});$('resultTitle').textContent=S.year+'年目の結果';$('surprise').textContent='予想外の出来事：'+surprise.text;$('changes').innerHTML=Object.keys(M).map(k=>{let d=S.v[k]-before[k];return '<div class="change">'+M[k].i+' '+M[k].n+' <b class="'+(d>=0?'up':'down')+'">'+(d>0?'+':'')+d+'</b> → '+S.v[k]+'</div>'}).join('');$('reasons').innerHTML=reasons.map(x=>'・'+x).join('<br>');let a=[];if(S.v.child>=70)a.push('子育ての選択肢が増えてきたと感じる。');if(S.v.stay>=55)a.push('地元で働く・関わる選択肢が前より見える。');if(S.v.equity<40)a.push('中心の地区は便利になったけど、うちの地区は置いていかれてる感じ。');if(S.v.fatigue>70)a.push('もう新しいことを増やすより、続け方を考えてほしい。');if(!a.length)a.push('少しずつ変わっているけど、まだ実感できるほどではないかな。');$('afterVoices').innerHTML=a.map(x=>'<div class="voice">👤 '+x+'</div>').join('');$('result').classList.remove('hidden');$('runYear').disabled=true;renderHistory();$('result').scrollIntoView({behavior:'smooth',block:'start'})}
function renderHistory(){$('history').innerHTML=S.history.map(h=>'<tr><td>'+h.year+'</td><td>'+(h.names.length?h.names.join(' / '):'なし')+'</td>'+['connection','youth','child','senior','stay','industry','tourism','equity','fatigue'].map(k=>'<td>'+h.v[k]+'</td>').join('')+'</tr>').join('')}
function next(){if(S.year>=5)return finish();S.year++;S.selected=[];S.event=null;S.currentBudgetBonus=S.nextBudgetBonus;S.nextBudgetBonus=0;$('result').classList.add('hidden');$('runYear').disabled=false;renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function finish(){let g=GOALS[S.goal],sc=[];Object.entries(g.t).forEach(([k,t])=>sc.push(k==='fatigue'?Math.min(1,t/Math.max(1,S.v[k])):Math.min(1,S.v[k]/t)));let ach=Math.round(sc.reduce((a,b)=>a+b,0)/sc.length*100);if(S.approach==='hybrid')ach=Math.min(100,ach+3);$('play').classList.add('hidden');$('ending').classList.remove('hidden');$('endingTitle').textContent=g.icon+' '+g.name+' × '+APPROACHES[S.approach].name;$('achievement').textContent=ach;$('endingLabel').textContent=ach>=90?'🏆 一貫したまちづくり':ach>=78?'🌟 方向性が見えてきた':ach>=65?'🧭 成果と課題がはっきりした':'🧪 データの読み方から再挑戦';let dif=Object.keys(M).filter(k=>k!=='fatigue').map(k=>({k,d:S.v[k]-START[k]})).sort((a,b)=>b.d-a.d);$('strengthReport').innerHTML=dif.slice(0,4).map(x=>'<li>'+M[x.k].n+'：'+START[x.k]+' → '+S.v[x.k]+'（'+(x.d>=0?'+':'')+x.d+'）</li>').join('');let c=[];Object.entries(g.t).forEach(([k,t])=>{let miss=k==='fatigue'?S.v[k]>t:S.v[k]<t;if(miss)c.push(M[k].n+'：現在'+S.v[k]+'／目標'+(k==='fatigue'?'≤':'≥')+t)});if(!c.length)c.push('目標値はすべて達成。次は「誰が負担したか」を考えてみよう。');$('challengeReport').innerHTML=c.slice(0,5).map(x=>'<li>'+x+'</li>').join('');let q=S.approach==='repair'?'課題を埋める一方で、南風原町がもともと持っていた強みを十分に使えたでしょうか。':S.approach==='strength'?'強みを伸ばす一方で、町外通勤や地区差などの課題を置き去りにしていませんか。':'強みと課題の両方を追った結果、どこかが中途半端になっていませんか。';$('endingQuestion').innerHTML='<b>最後の問い：</b>'+q;window.scrollTo({top:0,behavior:'smooth'})}
function start(){let a=$('approachGrid').querySelector('.choice.active').dataset.k,g=$('goalGrid').querySelector('.choice.active').dataset.k;S={year:1,approach:a,goal:g,v:{...START},selected:[],active:[],neglect:{},history:[],event:null,currentBudgetBonus:0,nextBudgetBonus:0};$('approachPill').textContent=APPROACHES[a].icon+' '+APPROACHES[a].name;$('goalPill').textContent=GOALS[g].icon+' '+GOALS[g].name;$('setup').classList.add('hidden');$('play').classList.remove('hidden');$('ending').classList.add('hidden');$('result').classList.add('hidden');$('runYear').disabled=false;renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function reset(){$('play').classList.add('hidden');$('ending').classList.add('hidden');$('setup').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
renderApproaches();renderGoals();$('start').onclick=start;$('runYear').onclick=runYear;$('nextYear').onclick=next;$('resetTop').onclick=reset;$('restart').onclick=reset;
})();